# Generated by Django 4.2.3 on 2024-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_employee_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="certificate",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
